### ISSUE TITLE
Not working with boolean devices (e.g. power plugs)

### ISSUE THREAD

**Issue by dersimn** [stampe123/node-red-contrib-node-hue#10]
Devices with just on/off field like [Osram Lightify Plug](https://www.amazon.de/Osram-Schnittstelle-Lightify-Systems-herk%C3%B6mmlicher-Leuchtmittel/dp/B00YSXBP90)

	"3": {
		"state": {
			"on": false,
			"alert": "none",
			"reachable": true
		},

causing error `"parameter, bri, not available"`.

**Comment by jdomeij** [comment]
I have added workaround for empty `bri`, not certain if it fixes the problem because i couldn't reproduce to see where it was triggered.

**Comment by dersimn** [comment]
Hm, ok now it's turning on, the label shows `on (0%)` (strange, eh?) but turns off again for no reason at the next polling intervall.

Do you have some kind of tutorial how to debug Node RED scripts? I'm just familiar with NodeJS.

**Comment by jdomeij** [comment]
`on (0%)` is not strange because i set the brightness to zero if it's not set. 
This node should not send new status during polling, most likely you have something that triggers on the updated values and send new value to the light. An example is enabling the "If msg arrives on input, pass through to output" on the dashboard switch node, which can trigger some strange behavior

Try adding an debug node that receives the same data as the node-hue output node,
