### ISSUE TITLE
Reconnecting hue brigde

### ISSUE THREAD

**Issue by rum0s** [stampe123/node-red-contrib-node-hue#4]
Hi stampe,

first of all, thank you very much, the nodes are working very well :)
I have a problem, when my bridge is offline and node-red already running. How can the connection be reestablished? The only fix is to change (like moving) the flow and "deploy" again.
Moreover what is meant by polling time? Is it possible to change the value? Mine is somehow fixed and not changeable

Best regards!

**Comment by jdomeij** [comment]
Hello and thanks

if you comment out the following block in the `hue-server.js` `LightServer.prototype.init` function
```
    if (err) {
      return callback(err);
    }
```
then it will ignore errors on initialization, this code is there because I wanted to detect invalid API key at startup. Not certain of how to handle this cleanly, need to think about how to solve it.

As for the polling time you can configure it on the hue bridge as the "Poll interval", this value is used to to read the state for the Hue lights and check if they have modified by external resource. These can be detected by checking if the event value is set to "update", this is not 100% correctly triggered because the Hue lights has some strange calculations which results that we get an update event on our own changes also (expected value differs to Hue value).

**Comment by rum0s** [comment]
Thank you very much for your quick and helpfull answer! It works very well now. As I turn off the brigde when I'm leaving home, I do not need to re-deploy the flow when coming back. Great!
